=== sooheon45/jeus8-bpm6/samples/ReverseProxy/WEB-INF/config/proxy-config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT config (single-server*, cluster-server*)>

<!-- single-server: proxy로 오는 해당 요청 -->
<!ELEMENT single-server (domain-name, rewriting?, path?, (directory-rule|accept-everything-rule))>

<!-- cluster-server: proxy로 오는 요청을 여러 서버에 round robin으로 보낼 때 설정 -->
<!ELEMENT cluster-server (server*, (directory-rule|accept-everything-rule))>  

<!-- server: cluster된 하나의 서버를 말함 -->
<!ELEMENT server (domain-name, rewriting?, path?)>

<!-- directory rule: proxy 서버에 대한 요청을 구분하기 위한 rule. directory 명으로 구부한다. path를 "/dir"으로 설정하면 HOSTNAME/dir 으로 요청에 맞는 server로 요청이 전달된다. -->
<!ELEMENT directory-rule (path)>

<!-- path: directory 설정 "/" 로 시작한다. -->
<!ELEMENT path (#PCDATA)>

<!-- accept-everthing-rule: 모든 요청에 대해서 해당 서버로 요청을 전달하기 위한 rule. 설정에서 가장 하위에 설정되어야 함 -->
<!ELEMENT accept-everything-rule EMPTY>

<!-- domain-name: 서버의 주소. HOSTNAME:PORT ex) www.server1.com, www.server2.com:9999 -->
<!ELEMENT domain-name (#PCDATA)>

<!-- rewriting: proxy 된 문서 내용 중 link 들 중에 절대 주소를 rewriting할 지 결정 여부. -->
<!ELEMENT rewriting (#PCDATA)>

=== sooheon45/jeus8-bpm6/samples/ReverseProxy/WEB-INF/config/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "proxy-config.dtd">

<config>
	<!-- proxy server의 주소가 www.proxy.com 이라고 가정 -->
	<!-- 아래는 www.proxy.com/server1/ 이하의 요청이 www.server1.com/content1 으로 전달 -->
	<single-server>
		<domain-name>www.server1.com</domain-name>
		<rewriting>true</rewriting>
		<path>/content1</path>
		<directory-rule>
			<path>/server1</path>
		</directory-rule>
	</single-server>

	<!-- 아래는 www.proxy.com/server2/ 이하의 요청이 www.server2.com의 8080 포트로 전달 -->
	<single-server>
		<domain-name>www.server2.com:8080</domain-name>
		<rewriting>true</rewriting>
		<directory-rule>
			<path>/server2</path>
		</directory-rule>
	</single-server>
	
	<!-- 아래는 위에서 설정한 요청을 제외한 요청에 대해서 www.server3.com 으로 전달 -->
	<single-server>
		<domain-name>www.server3.com</domain-name>
		<rewriting>true</rewriting>
		<accept-everything-rule/>
	</single-server>
</config>

=== sooheon45/jeus8-bpm6/samples/ReverseProxy/WEB-INF/config/proxy-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "proxy-config.dtd">

<config>
	<single-server>
		<domain-name>www.mydomain.com:8080</domain-name>
		<rewriting>true</rewriting>
		<path>/content</path>
		<directory-rule>
			<path>/remote</path>
		</directory-rule>
	</single-server>

	<single-server>
		<domain-name>www.mydomain.com:8080</domain-name>
		<rewriting>true</rewriting>
		<path>/content</path>
		<directory-rule>
			<path>/remote</path>
		</directory-rule>
	</single-server>

	<cluster-server>
		<server>
			<domain-name>www.otherdomain.com</domain-name>
			<rewriting>true</rewriting>
		</server>

		<server>
			<domain-name>www.otherdomain1.com</domain-name>
			<rewriting>true</rewriting>
		</server>

		<accept-everything-rule/> 
	</cluster-server>
</config>
